# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/ui/serial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Serial(object):
    def setupUi(self, Serial):
        Serial.setObjectName("Serial")
        Serial.resize(283, 138)
        self.verticalLayout = QtWidgets.QVBoxLayout(Serial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_port = QtWidgets.QComboBox(Serial)
        self.cb_port.setObjectName("cb_port")
        self.verticalLayout.addWidget(self.cb_port)
        self.cb_baud = QtWidgets.QComboBox(Serial)
        self.cb_baud.setObjectName("cb_baud")
        self.cb_baud.addItem("")
        self.cb_baud.addItem("")
        self.verticalLayout.addWidget(self.cb_baud)
        spacerItem = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_disconnect = QtWidgets.QPushButton(Serial)
        self.bt_disconnect.setEnabled(False)
        self.bt_disconnect.setObjectName("bt_disconnect")
        self.horizontalLayout.addWidget(self.bt_disconnect)
        self.bt_connect = QtWidgets.QPushButton(Serial)
        self.bt_connect.setObjectName("bt_connect")
        self.horizontalLayout.addWidget(self.bt_connect)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Serial)
        QtCore.QMetaObject.connectSlotsByName(Serial)

    def retranslateUi(self, Serial):
        _translate = QtCore.QCoreApplication.translate
        Serial.setWindowTitle(_translate("Serial", "Form"))
        self.cb_baud.setItemText(0, _translate("Serial", "115200"))
        self.cb_baud.setItemText(1, _translate("Serial", "9600"))
        self.bt_disconnect.setText(_translate("Serial", "Disconnect"))
        self.bt_connect.setText(_translate("Serial", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Serial = QtWidgets.QWidget()
    ui = Ui_Serial()
    ui.setupUi(Serial)
    Serial.show()
    sys.exit(app.exec_())
